name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling==0.13.0
  - xeus-python
  - matplotlib-base
  - notebook
  - pip
  - pip:
    - cirq
    - pyquil
    - qiskit == 0.23.6
    - quantuminspire
