name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling==0.9
  - xeus-python
  - matplotlib-base
  - notebook
  - pip
  - pip:
    - cirq
    - pyquil
    - qiskit
    - quantuminspire
