#!/bin/bash

# Get GitLab repo
git clone https://gitlab.com/mmoelle1/LibKet $HOME/LibKet

cd $HOME/LibKet

# Update submodules 
git submodule update --init --recursive

# Build LibKet external libraries
mkdir build
cd build
cmake -DLIBKET_BUILD_C_API=OFF -DLIBKET_BUILD_PYTHON_API=OFF -DLIBKET_BUILD_EXAMPLES=OFF -DLIBKET_BUILD_UNITTESTS=OFF -DLIBKET_USE_PCH=OFF -DLIBKET_WITH_CIRQ=ON -DLIBKET_WITH_CQASM=ON -DLIBKET_WITH_OPENMP=OFF -DLIBKET_WITH_OPENQASM=ON -DLIBKET_WITH_OPENQL=ON -DLIBKET_WITH_QUEST=ON -DLIBKET_WITH_QUIL=ON -DLIBKET_WITH_QX=ON ..
make

ls -alR

which xcpp
